# Generated by Django 4.2.7 on 2023-11-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(max_length=50, verbose_name='Широта')),
                ('longitude', models.FloatField(max_length=50, verbose_name='Долгота')),
                ('height', models.IntegerField(verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=6, null=True, verbose_name='Зима')),
                ('summer', models.CharField(blank=True, max_length=6, null=True, verbose_name='Лето')),
                ('autumn', models.CharField(blank=True, max_length=6, null=True, verbose_name='Осень')),
                ('spring', models.CharField(blank=True, max_length=6, null=True, verbose_name='Весна')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('fam', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('otc', models.CharField(max_length=50, verbose_name='Отчество')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Электронная почта')),
                ('tel', models.CharField(max_length=50, unique=True, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название')),
                ('beautyTitle', models.CharField(default=None, max_length=50, verbose_name='Форма рельефа')),
                ('other_titles', models.CharField(blank=True, max_length=50, null=True, verbose_name='Другое название')),
                ('connect', models.CharField(max_length=50, verbose_name='Связь')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('pending', 'Ожидается'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='new', max_length=10, verbose_name='Статус')),
                ('coord_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='Уровень')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Фото')),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval', verbose_name='Перевал-фото')),
            ],
        ),
    ]
