# Generated by Django 4.2.7 on 2023-11-29 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='pereval',
        ),
        migrations.AddField(
            model_name='pereval',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.images', verbose_name='Фото'),
        ),
    ]
