# Generated by Django 4.2.7 on 2023-11-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0002_remove_images_pereval_pereval_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RenameField(
            model_name='coords',
            old_name='width',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.pereval', verbose_name='Перевал-фото'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Зима'),
        ),
    ]
