# Generated by Django 4.2.7 on 2023-11-29 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0003_alter_user_options_rename_width_coords_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='coord_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
    ]
