# Generated by Django 4.2.7 on 2023-11-29 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0004_alter_pereval_coord_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='coords',
            old_name='latitude',
            new_name='width',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='data',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='images',
            name='pereval',
        ),
        migrations.AddField(
            model_name='pereval',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.images', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Зима'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='coord_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
    ]
