# Generated by Django 4.2.7 on 2023-11-29 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pereval', '0006_rename_width_coords_latitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coords',
            options={'verbose_name': 'Координата', 'verbose_name_plural': 'Координаты'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Категория сложности', 'verbose_name_plural': 'Категория сложности'},
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='coord_id',
        ),
        migrations.RemoveField(
            model_name='pereval',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='pereval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval'),
        ),
        migrations.AddField(
            model_name='pereval',
            name='coords',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.coords', verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='level',
            name='autumn',
            field=models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б')], max_length=6, null=True, verbose_name='Осень'),
        ),
        migrations.AlterField(
            model_name='level',
            name='spring',
            field=models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б')], max_length=6, null=True, verbose_name='Весна'),
        ),
        migrations.AlterField(
            model_name='level',
            name='summer',
            field=models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б')], max_length=6, null=True, verbose_name='Лето'),
        ),
        migrations.AlterField(
            model_name='level',
            name='winter',
            field=models.CharField(blank=True, choices=[('1a', '1А'), ('1b', '1Б'), ('2a', '2А'), ('2b', '2Б')], max_length=6, null=True, verbose_name='Зима'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='connect',
            field=models.CharField(max_length=50, verbose_name='Вид соединения'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pereval.user', verbose_name='Пользователь'),
        ),
    ]
